# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436374066ecc0ea7a152f105b7c7e9a325e051b76a1719d90864817aba9562c5edcde949faec675f382b347223641bc24e63035332b474a3411dcb219a36bfcf

test:
  secret_key_base: 0b28ab78bf64c409a122b018e4a5618e6831e43d7ea77604825c5886f74ad17e262f61ea79c6b5c14512fce505514b986970f665a6227c852fa66e78c43c6dc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
